export const GET_ALL_SCALES = "GET_ALL_SCALES";
export const SCALES_ERROR = "SCALES_ERROR";
export const GET_MEASUREMENTS_PER_SCALE = "GET_MEASUREMENTS_PER_SCALE";
export const MEASUREMENTS_PER_SCALE_ERROR = "MEASUREMENTS_PER_SCALE_ERROR";
export const GET_ALL_OPERATORS = "GET_ALL_OPERATORS";
export const OPERATORS_ERROR = "OPERATORS_ERROR";
